# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploaded',
            old_name='itimestamp',
            new_name='itimestamp_upload',
        ),
        migrations.AddField(
            model_name='fileuploaded',
            name='itimestamp_touch',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 6, 0, 17, 362642, tzinfo=utc), verbose_name='Time used'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileuploaded',
            name='ifile',
            field=models.FileField(max_length=500, upload_to='/Users/rsaito/Sites/WebSys_UCSD2/UCSD_IMM_beta4/UCSD_IMM_WorkSpace/Media/FilesUploaded/Ver0p1/%Y/%m/%d', verbose_name='Uploaded file'),
        ),
    ]
