# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0002_auto_20160215_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workchunk_class',
            options={'verbose_name': 'Work chunk class', 'verbose_name_plural': 'Work chunk classes'},
        ),
        migrations.AlterModelOptions(
            name='workchunk_served',
            options={'verbose_name': 'How the product was useful afterward', 'verbose_name_plural': 'How the product was useful afterward'},
        ),
        migrations.AddField(
            model_name='workchunk_plan',
            name='chunk_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appWorkChunkPlanner.WorkChunk_Class'),
        ),
    ]
