# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0003_auto_20160215_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='workchunk_plan',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned begin time'),
        ),
        migrations.AddField(
            model_name='workchunk_plan',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned finish time'),
        ),
    ]
