# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 23:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0004_auto_20160215_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workchunk_plan',
            name='begin_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 15, 23, 58, 8, 81233, tzinfo=utc), verbose_name='Planned begin time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workchunk_plan',
            name='chunk_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWorkChunkPlanner.WorkChunk_Class'),
        ),
        migrations.AlterField(
            model_name='workchunk_plan',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 15, 23, 59, 18, 174611, tzinfo=utc), verbose_name='Planned finish time'),
            preserve_default=False,
        ),
    ]
