# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0007_auto_20160216_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workchunk_plan',
            old_name='proj',
            new_name='project',
        ),
    ]
