# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0008_auto_20160216_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workchunk_record',
            name='rec_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
