# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0011_auto_20160217_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='workchunk_plan',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Plan accomplished?'),
        ),
    ]
