# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0012_workchunk_plan_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workchunk_served',
            name='worked_chunk',
        ),
        migrations.AddField(
            model_name='workchunk_served',
            name='worked_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appWorkChunkPlanner.WorkChunk_Plan'),
        ),
    ]
