# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0013_auto_20160226_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workchunk_served',
            name='worked_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWorkChunkPlanner.WorkChunk_Plan'),
        ),
    ]
