# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0014_auto_20160226_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkChunk_Plan_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Plan status',
                'verbose_name': 'Plan status',
            },
        ),
        migrations.RemoveField(
            model_name='workchunk_plan',
            name='complete',
        ),
        migrations.AlterField(
            model_name='workchunk_record',
            name='weight_per_time',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='workchunk_plan',
            name='plan_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appWorkChunkPlanner.WorkChunk_Plan_Status'),
        ),
    ]
