# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0016_auto_20160305_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='workchunk_plan',
            name='plan_cancel_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
