# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkChunkPlanner', '0018_workchunk_plan_timestamp_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkChunk_Plan_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_weight', models.FloatField(default=0.8)),
                ('link_note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='WorkChunk_Plan_Link_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='workchunk_plan_link',
            name='link_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWorkChunkPlanner.WorkChunk_Plan_Link_Type', verbose_name='Link type'),
        ),
        migrations.AddField(
            model_name='workchunk_plan_link',
            name='plan_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_src', to='appWorkChunkPlanner.WorkChunk_Plan', verbose_name='Source plan'),
        ),
        migrations.AddField(
            model_name='workchunk_plan_link',
            name='plan_tgt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tgt', to='appWorkChunkPlanner.WorkChunk_Plan', verbose_name='Target plan'),
        ),
    ]
